#!/bin/bash
apache_directory=/etc/apache2/sites-available
vhost_name=$1
script_location="$( dirname "${BASH_SOURCE[0]}"  )"
vhost_file="$apache_directory"/"$vhost_name".conf
if [ "$1" == "" ]; then
	echo Please specify a vhost name as a command line argument.
	exit 2
fi
if [ -f "$apache_directory"/"$vhost_name".conf ]; then
	echo Host already exists. Won\'t do anything.
	exit 2
fi
if [ -d $apache_directory ]; then
	# create .conf file for apache
	sudo cp "$script_location"/resources/vhost_dummy.conf "$vhost_file"
	sudo perl -p -i -e "s/HOSTNAME/$vhost_name/g" "$vhost_file"

	# modify /etc/hosts
	file_contents=127.0.0.1\\t"$vhost_name"\\n$(cat /etc/hosts)
	sudo sh -c "echo \"$file_contents\" > /etc/hosts"

	# enable site, restart apache
	sudo a2ensite $vhost_name
	sudo apachectl -k restart

	# terminate script
	echo Host $vhost_name created!
	exit 0
else
	echo Default directory $default_directory does not exists.
	exit 2
fi
