#!/bin/bash


if [ -z "$1" ]; then
	echo "Provide a list of tags (__tags__cool__likeeff__even-with-spaces__example__overandout) as the first argument"
	exit 1
fi
listOfTags=$1

directoryForCode=~/webdev/${listOfTags}
mkdir $directoryForCode || exit $?
cd $directoryForCode

git init || exit $?
ignorefile=".gitignore"
echo "node_modules" > ./${ignorefile}
echo "public/" > ./${ignorefile}
echo ".idea" > ./${ignorefile}
git commit --all
git commit -m ".gitignore file filled with various typical values"

directoryForNotes=~/projects/${listOfTags} 
mkdir $directoryForNotes || exit $?
cd $directoryForNotes
touch ~/secrets/zugangsdaten/${listOfTags}
ln -s ~/secrets/zugangsdaten/${listOfTags} zugangsdaten
