#!/bin/bash

encrypted=$HOME/documents/passwords
outfile=/tmp/passwords.tmp.txt
copyfile=/tmp/passwords.tmp.txt.copy
if [ -f $outfile ] || [ -f $copyfile ]; then
	echo 'Output file already in tmp folder. Aborting.'
	exit 1
fi
gpg --output $outfile $encrypted
cp $outfile $copyfile
vim $outfile
originalmd5=`cat $copyfile | md5sum`
editedmd5=`cat $outfile | md5sum`
if [ "$originalmd5" == "$editedmd5" ]; then
	# file has not been modified. Do nothing.
	echo 'File has not been modified.'
else
	# File has been modified. Update password file.
	echo 'Updating the password file.'
	gpg --output $encrypted -c $outfile
fi

function finish() {
	rm $outfile
	rm $copyfile
}
trap finish EXIT
