#!/bin/bash

# toggle synaptic touchpad on/off

# get id number


id=$(xinput list | grep -i touchpad | perl -p -e "s/.*id=([0-9]+).*/\$1/")

enabled=$(xinput --list-props $id | grep -iE "Device Enabled.*:.*1")

if [[ -n $enabled ]]; then
    echo is enabled. Disable now.
    xinput --disable $id
else
    echo is not enabled. Enable now.
    xinput --enable $id
fi
